version: '3'

services:
  api:
    container_name: contelizer_api
    build: 
      context: ./src/backend
    command: >
      sh -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./src/backend/:/api
    ports:
      - "8000:8000"

  frontend:
    container_name: contelizer_frontend
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/:/frontend
      - /frontend/node_modules